name: 'Node.JS Single Executable Application Action'
description: 'Builds a Node.JS SEA (Single Executable Application)'
author: 'bryopsida'
inputs:
  working-dir:
    type: 'string'
  executable-name:
    type: 'string'
  sea-config-path:
    type: 'string'
  esbuild-cmd:
    type: 'string'
  sign-executable:
    type: 'boolean'

outputs:
  executable-path:
    description: 'Path to the executable'
    type: 'string'

runs:
  using: node20
  main: dist/index.js
